user:
  length_of_name: 50
  length_of_email: 255
  length_of_password: 6
  gravatar_size: 80
  remember_user: 1
  per_page: 30
gravatar:
size: 50
checkbox: "1"
Post:
  num_post: 5
  size_image: 5
  resize_height: 400
  resize_width: 400
  content_size: 140
  avatar_size: 50
micropst:
  per_page: 10
  